version: "3.7"
services:
  db:
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./matcha.sql:/docker-entrypoint-initdb.d/matcha.sql
    environment:
      POSTGRES_USER: matcha
      POSTGRES_PASSWORD: matcha
      POSTGRES_DB: matcha
    restart: always
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 80:8080
