version: "3.7"
services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db:/var/lib/mysql
      - ./matcha.sql:/docker-entrypoint-initdb.d/matcha.sql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: matcha
      MYSQL_USER: matcha
      MYSQL_PASSWORD: matcha
    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    depends_on:
      - db
    ports:
      - 8080:80
